enum class DungeonName {
    THE_FORGOTTEN_HALLS, HOLLOWED_DESCENT, ABYSSAL_FORGE, CURSED_WELL, SHATTERED_SANCTUM, WRETCHED_LAIR,
    FORSAKEN_VAULT, ASHEN_TOMB, LOST_CRYPT, VOIDBOUND_KEEP, THE_BROKEN_SPIRAL, OBLIVION_DEPTHS, GRIM_OBELISK,
    THE_FALLEN_REACH, SOULFIRE_CATACOMBS, ETERNAL_VIGIL, THE_BLEAK_HORIZON, CRIMSON_SCOURGE, FROSTWORN_HOLD,
    THE_ANGUISH_HALL
}