enum class RoomName {
    THRONE_OF_DESPAIR, VILE_WELL, WEEPING_CHAMBER, THE_SCORCHED_ALTAR, THE_SHADOWED_VAULT, HALLS_OF_MOURNING,
    BLOODSTAINED_SANCTUM, CRUSHED_GRAVE, THE_ECLIPSED_REST, THE_FROSTBOUND_CHAMBER, SINISTER_PIT, FORGOTTEN_TEMPLE,
    THE_BLOOD_OOZE, THE_OBSIDIAN_RIFT, THE_CRYPTIC_VAULT, RUNE_SCARRED_HALL, THE_WARPED_PANOPTICON, THE_ASHEN_BARRACKS,
    THE_VENGEFUL_GLADE, THE_WICKED_OBELISK
}