enum class MonstersName {
    KERRY_KAVERGA, ELBA_GINA, SUSANA_ORIA, ROSA_MELANO, ANA_BOHUELES,
    ESTEBAN_DATO, TOMAS_TURBA, ELBA_SURA, ARMANDO_ESTEBAN_QUITO,
    DOLORES_DEL_ANO, CESAR_HINCHADO, AITOR_MENTA, PERE_GIL,
    ZOILA_CERDA, ALAN_BRADO, LESBIA_NOZA, PILAR_OSO_AMOROSO,
    ELBA_LASTIMA, TOMI_SIPOTE, DIXON_MAYAS, TOM_ASPERUANO
}